-- 0001_init.up.sql
--
-- Baseline schema. Full DDL equivalent to a first-boot GORM AutoMigrate of the
-- 15 core models (see internal/database/database.go: Connect -> AutoMigrate).
-- Generated by pg_dump of a freshly AutoMigrated PostgreSQL 16 database so the
-- versioned track (SKIP_AUTOMIGRATE=true) can build the schema from an empty DB.
-- New schema changes MUST be added as 0002+ files, never via GORM tags alone.
-- See ORM_RULES.md (Migrations section).

--
--

--
-- Name: announcements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.announcements (
    id bigint NOT NULL,
    class_id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    body text,
    attachments jsonb,
    created_at timestamp with time zone
);

--
-- Name: announcements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.announcements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: announcements_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.announcements_id_seq OWNED BY public.announcements.id;

--
-- Name: class_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_members (
    id bigint NOT NULL,
    class_id bigint NOT NULL,
    user_id bigint NOT NULL,
    joined_at timestamp with time zone
);

--
-- Name: class_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.class_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: class_members_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.class_members_id_seq OWNED BY public.class_members.id;

--
-- Name: classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.classes (
    id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    section character varying(100),
    invite_code character varying(8) NOT NULL,
    cover_image text,
    grades_announced boolean DEFAULT false NOT NULL,
    passing_threshold bigint DEFAULT 60 NOT NULL,
    block_announce_with_pending boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone
);

--
-- Name: classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: classes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.classes_id_seq OWNED BY public.classes.id;

--
-- Name: exam_attempts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_attempts (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    exam_id bigint NOT NULL,
    started_at timestamp with time zone,
    submitted_at timestamp with time zone,
    score numeric DEFAULT 0 NOT NULL,
    status character varying(30) DEFAULT 'in_progress'::character varying NOT NULL,
    graded_notified boolean DEFAULT false NOT NULL,
    draft_answers jsonb,
    draft_saved_at timestamp with time zone
);

--
-- Name: exam_attempts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.exam_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: exam_attempts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.exam_attempts_id_seq OWNED BY public.exam_attempts.id;

--
-- Name: exam_classes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_classes (
    id bigint NOT NULL,
    exam_id bigint NOT NULL,
    class_id bigint NOT NULL
);

--
-- Name: exam_classes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.exam_classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: exam_classes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.exam_classes_id_seq OWNED BY public.exam_classes.id;

--
-- Name: exams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exams (
    id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    duration_minutes bigint DEFAULT 60 NOT NULL,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    reset_at timestamp with time zone,
    reminder_sent_at timestamp with time zone,
    email_reminder1h_sent_at timestamp with time zone,
    email_reminder_start_sent_at timestamp with time zone,
    created_at timestamp with time zone,
    shuffle_questions boolean DEFAULT false,
    show_results_after boolean DEFAULT true,
    passing_score bigint DEFAULT 50,
    is_practice boolean DEFAULT false,
    is_draft boolean DEFAULT false
);

--
-- Name: exams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.exams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: exams_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.exams_id_seq OWNED BY public.exams.id;

--
-- Name: folders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.folders (
    id bigint NOT NULL,
    teacher_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp with time zone
);

--
-- Name: folders_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.folders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: folders_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.folders_id_seq OWNED BY public.folders.id;

--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    type character varying(20) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    link_to character varying(255),
    read boolean DEFAULT false,
    created_at timestamp with time zone
);

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: notifications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;

--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    token_hash character varying(64) NOT NULL,
    expires_at timestamp with time zone,
    used_at timestamp with time zone,
    created_at timestamp with time zone
);

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.password_reset_tokens_id_seq OWNED BY public.password_reset_tokens.id;

--
-- Name: problems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.problems (
    id bigint NOT NULL,
    exam_id bigint,
    is_bank boolean DEFAULT false NOT NULL,
    teacher_id bigint,
    class_id bigint,
    folder_id bigint,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    type character varying(20) DEFAULT 'coding'::character varying NOT NULL,
    points bigint DEFAULT 10 NOT NULL,
    difficulty character varying(20) DEFAULT 'medium'::character varying NOT NULL,
    starter_code text,
    hints text,
    time_limit_ms bigint DEFAULT 2000 NOT NULL,
    memory_limit_kb bigint DEFAULT 262144 NOT NULL,
    order_index bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone,
    options jsonb,
    correct_option_ids jsonb,
    multiple_correct boolean DEFAULT false,
    explanation text,
    max_word_count bigint DEFAULT 500,
    rubric text,
    require_manual_grading boolean DEFAULT false,
    image_url text,
    tags jsonb DEFAULT '[]'::jsonb
);

--
-- Name: problems_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.problems_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: problems_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.problems_id_seq OWNED BY public.problems.id;

--
-- Name: submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.submissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    problem_id bigint NOT NULL,
    exam_id bigint NOT NULL,
    exam_attempt_id bigint,
    type character varying(20) DEFAULT 'coding'::character varying NOT NULL,
    language character varying(20),
    code text,
    selected_options jsonb,
    text_answer text,
    status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    teacher_feedback text,
    passed_count bigint DEFAULT 0 NOT NULL,
    total_count bigint DEFAULT 0 NOT NULL,
    score numeric DEFAULT 0 NOT NULL,
    execution_time_ms bigint DEFAULT 0,
    memory_kb bigint DEFAULT 0,
    submitted_at timestamp with time zone
);

--
-- Name: submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: submissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.submissions_id_seq OWNED BY public.submissions.id;

--
-- Name: test_cases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_cases (
    id bigint NOT NULL,
    problem_id bigint NOT NULL,
    input text NOT NULL,
    expected_output text NOT NULL,
    is_sample boolean DEFAULT false NOT NULL,
    points bigint DEFAULT 0 NOT NULL,
    order_index bigint DEFAULT 0 NOT NULL
);

--
-- Name: test_cases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.test_cases_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: test_cases_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.test_cases_id_seq OWNED BY public.test_cases.id;

--
-- Name: test_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.test_results (
    id bigint NOT NULL,
    submission_id bigint NOT NULL,
    test_case_id bigint NOT NULL,
    passed boolean DEFAULT false NOT NULL,
    actual_output text,
    execution_time_ms bigint DEFAULT 0,
    memory_kb bigint DEFAULT 0,
    status character varying(30)
);

--
-- Name: test_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.test_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: test_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.test_results_id_seq OWNED BY public.test_results.id;

--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profiles (
    id bigint NOT NULL,
    user_id bigint,
    bio text,
    avatar_url text,
    notify_email boolean DEFAULT true,
    notify_push boolean DEFAULT true,
    notify_exam_reminders boolean DEFAULT true,
    notify_results boolean DEFAULT false,
    notify_exam_email boolean DEFAULT true,
    block_announce_with_pending boolean DEFAULT true,
    default_exam_draft boolean DEFAULT true,
    default_passing_threshold bigint DEFAULT 60
);

--
-- Name: user_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: user_profiles_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_profiles_id_seq OWNED BY public.user_profiles.id;

--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    password_hash text NOT NULL,
    role character varying(20) NOT NULL,
    name character varying(255) NOT NULL,
    google_id character varying(64),
    created_at timestamp with time zone
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;

--
-- Name: announcements id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements ALTER COLUMN id SET DEFAULT nextval('public.announcements_id_seq'::regclass);

--
-- Name: class_members id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_members ALTER COLUMN id SET DEFAULT nextval('public.class_members_id_seq'::regclass);

--
-- Name: classes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes ALTER COLUMN id SET DEFAULT nextval('public.classes_id_seq'::regclass);

--
-- Name: exam_attempts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempts ALTER COLUMN id SET DEFAULT nextval('public.exam_attempts_id_seq'::regclass);

--
-- Name: exam_classes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_classes ALTER COLUMN id SET DEFAULT nextval('public.exam_classes_id_seq'::regclass);

--
-- Name: exams id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exams ALTER COLUMN id SET DEFAULT nextval('public.exams_id_seq'::regclass);

--
-- Name: folders id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folders ALTER COLUMN id SET DEFAULT nextval('public.folders_id_seq'::regclass);

--
-- Name: notifications id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications ALTER COLUMN id SET DEFAULT nextval('public.notifications_id_seq'::regclass);

--
-- Name: password_reset_tokens id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens ALTER COLUMN id SET DEFAULT nextval('public.password_reset_tokens_id_seq'::regclass);

--
-- Name: problems id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problems ALTER COLUMN id SET DEFAULT nextval('public.problems_id_seq'::regclass);

--
-- Name: submissions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions ALTER COLUMN id SET DEFAULT nextval('public.submissions_id_seq'::regclass);

--
-- Name: test_cases id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_cases ALTER COLUMN id SET DEFAULT nextval('public.test_cases_id_seq'::regclass);

--
-- Name: test_results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_results ALTER COLUMN id SET DEFAULT nextval('public.test_results_id_seq'::regclass);

--
-- Name: user_profiles id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles ALTER COLUMN id SET DEFAULT nextval('public.user_profiles_id_seq'::regclass);

--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);

--
-- Name: announcements announcements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.announcements
    ADD CONSTRAINT announcements_pkey PRIMARY KEY (id);

--
-- Name: class_members class_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT class_members_pkey PRIMARY KEY (id);

--
-- Name: classes classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT classes_pkey PRIMARY KEY (id);

--
-- Name: exam_attempts exam_attempts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempts
    ADD CONSTRAINT exam_attempts_pkey PRIMARY KEY (id);

--
-- Name: exam_classes exam_classes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_classes
    ADD CONSTRAINT exam_classes_pkey PRIMARY KEY (id);

--
-- Name: exams exams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pkey PRIMARY KEY (id);

--
-- Name: folders folders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.folders
    ADD CONSTRAINT folders_pkey PRIMARY KEY (id);

--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);

--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);

--
-- Name: problems problems_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problems
    ADD CONSTRAINT problems_pkey PRIMARY KEY (id);

--
-- Name: submissions submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT submissions_pkey PRIMARY KEY (id);

--
-- Name: test_cases test_cases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_cases
    ADD CONSTRAINT test_cases_pkey PRIMARY KEY (id);

--
-- Name: test_results test_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_results
    ADD CONSTRAINT test_results_pkey PRIMARY KEY (id);

--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);

--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: idx_announcements_class_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_announcements_class_id ON public.announcements USING btree (class_id);

--
-- Name: idx_announcements_teacher_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_announcements_teacher_id ON public.announcements USING btree (teacher_id);

--
-- Name: idx_class_members_class_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_class_members_class_id ON public.class_members USING btree (class_id);

--
-- Name: idx_class_members_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_class_members_user_id ON public.class_members USING btree (user_id);

--
-- Name: idx_class_user; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_class_user ON public.class_members USING btree (class_id, user_id);

--
-- Name: idx_classes_invite_code; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_classes_invite_code ON public.classes USING btree (invite_code);

--
-- Name: idx_classes_teacher_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_classes_teacher_id ON public.classes USING btree (teacher_id);

--
-- Name: idx_exam_attempts_exam_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exam_attempts_exam_id ON public.exam_attempts USING btree (exam_id);

--
-- Name: idx_exam_attempts_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exam_attempts_user_id ON public.exam_attempts USING btree (user_id);

--
-- Name: idx_exam_class; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_exam_class ON public.exam_classes USING btree (exam_id, class_id);

--
-- Name: idx_exam_classes_class_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exam_classes_class_id ON public.exam_classes USING btree (class_id);

--
-- Name: idx_exam_classes_exam_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exam_classes_exam_id ON public.exam_classes USING btree (exam_id);

--
-- Name: idx_exams_reset_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exams_reset_at ON public.exams USING btree (reset_at);

--
-- Name: idx_exams_teacher_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_exams_teacher_id ON public.exams USING btree (teacher_id);

--
-- Name: idx_folders_teacher_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_folders_teacher_id ON public.folders USING btree (teacher_id);

--
-- Name: idx_notifications_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_user_id ON public.notifications USING btree (user_id);

--
-- Name: idx_password_reset_tokens_token_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_password_reset_tokens_token_hash ON public.password_reset_tokens USING btree (token_hash);

--
-- Name: idx_password_reset_tokens_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_password_reset_tokens_user_id ON public.password_reset_tokens USING btree (user_id);

--
-- Name: idx_problems_class_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_problems_class_id ON public.problems USING btree (class_id);

--
-- Name: idx_problems_exam_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_problems_exam_id ON public.problems USING btree (exam_id);

--
-- Name: idx_problems_folder_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_problems_folder_id ON public.problems USING btree (folder_id);

--
-- Name: idx_problems_is_bank; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_problems_is_bank ON public.problems USING btree (is_bank);

--
-- Name: idx_problems_teacher_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_problems_teacher_id ON public.problems USING btree (teacher_id);

--
-- Name: idx_submissions_exam_attempt_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_submissions_exam_attempt_id ON public.submissions USING btree (exam_attempt_id);

--
-- Name: idx_submissions_exam_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_submissions_exam_id ON public.submissions USING btree (exam_id);

--
-- Name: idx_submissions_problem_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_submissions_problem_id ON public.submissions USING btree (problem_id);

--
-- Name: idx_submissions_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_submissions_user_id ON public.submissions USING btree (user_id);

--
-- Name: idx_test_cases_problem_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_test_cases_problem_id ON public.test_cases USING btree (problem_id);

--
-- Name: idx_test_results_submission_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_test_results_submission_id ON public.test_results USING btree (submission_id);

--
-- Name: idx_test_results_test_case_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_test_results_test_case_id ON public.test_results USING btree (test_case_id);

--
-- Name: idx_user_exam_attempt; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_user_exam_attempt ON public.exam_attempts USING btree (user_id, exam_id);

--
-- Name: idx_user_profiles_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_user_profiles_user_id ON public.user_profiles USING btree (user_id);

--
-- Name: idx_users_email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_users_email ON public.users USING btree (email);

--
-- Name: idx_users_google_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_google_id ON public.users USING btree (google_id);

--
-- Name: class_members fk_class_members_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT fk_class_members_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: class_members fk_classes_members; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_members
    ADD CONSTRAINT fk_classes_members FOREIGN KEY (class_id) REFERENCES public.classes(id);

--
-- Name: classes fk_classes_teacher; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.classes
    ADD CONSTRAINT fk_classes_teacher FOREIGN KEY (teacher_id) REFERENCES public.users(id);

--
-- Name: exam_attempts fk_exam_attempts_exam; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempts
    ADD CONSTRAINT fk_exam_attempts_exam FOREIGN KEY (exam_id) REFERENCES public.exams(id);

--
-- Name: submissions fk_exam_attempts_submissions; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fk_exam_attempts_submissions FOREIGN KEY (exam_attempt_id) REFERENCES public.exam_attempts(id);

--
-- Name: exam_attempts fk_exam_attempts_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_attempts
    ADD CONSTRAINT fk_exam_attempts_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: exam_classes fk_exam_classes_class; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_classes
    ADD CONSTRAINT fk_exam_classes_class FOREIGN KEY (class_id) REFERENCES public.classes(id);

--
-- Name: exam_classes fk_exams_exam_classes; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_classes
    ADD CONSTRAINT fk_exams_exam_classes FOREIGN KEY (exam_id) REFERENCES public.exams(id);

--
-- Name: problems fk_exams_problems; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problems
    ADD CONSTRAINT fk_exams_problems FOREIGN KEY (exam_id) REFERENCES public.exams(id);

--
-- Name: exams fk_exams_teacher; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT fk_exams_teacher FOREIGN KEY (teacher_id) REFERENCES public.users(id);

--
-- Name: problems fk_problems_folder; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.problems
    ADD CONSTRAINT fk_problems_folder FOREIGN KEY (folder_id) REFERENCES public.folders(id) ON DELETE SET NULL;

--
-- Name: test_cases fk_problems_test_cases; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_cases
    ADD CONSTRAINT fk_problems_test_cases FOREIGN KEY (problem_id) REFERENCES public.problems(id);

--
-- Name: submissions fk_submissions_problem; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fk_submissions_problem FOREIGN KEY (problem_id) REFERENCES public.problems(id);

--
-- Name: test_results fk_submissions_test_results; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_results
    ADD CONSTRAINT fk_submissions_test_results FOREIGN KEY (submission_id) REFERENCES public.submissions(id);

--
-- Name: submissions fk_submissions_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.submissions
    ADD CONSTRAINT fk_submissions_user FOREIGN KEY (user_id) REFERENCES public.users(id);

--
-- Name: test_results fk_test_results_test_case; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.test_results
    ADD CONSTRAINT fk_test_results_test_case FOREIGN KEY (test_case_id) REFERENCES public.test_cases(id);

--
--

