run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosimple

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-use-default: false
  exclude-dirs:
    - frontend
    - book
