$pdf_mode = 5;           # xelatex
$xelatex = 'xelatex -interaction=nonstopmode -synctex=1 %O %S';
$bibtex_use = 2;         # run biber
$out_dir = '.';
@default_files = ('main.tex');
$clean_ext = 'bbl run.xml synctex.gz xdv fdb_latexmk fls';
